services:
  ground-station:
    build: .
    command: python ground_station.py
    ports:
      - "8000:8000"
    volumes:
      - ./mission_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  sat-alpha:
    build: .
    command: python satellite_node.py
    depends_on:
      - ground-station
    volumes:
      - ./mission_data:/app/data
    environment:
      - SAT_NAME=SAT-ALPHA
      - PYTHONUNBUFFERED=1
      - TLE_L1=1 25544U 98067A   26126.52495471  .00016717  00000-0  10270-3 0  9011
      - TLE_L2=2 25544  51.6442  10.5153 0004445 220.3102 210.3102 15.48815327306221
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  sat-bravo:
    build: .
    command: python satellite_node.py
    depends_on:
      - ground-station
    volumes:
      - ./mission_data:/app/data
    environment:
      - SAT_NAME=SAT-BRAVO
      - PYTHONUNBUFFERED=1
      - TLE_L1=1 25544U 98067A   26126.52495471  .00016717  00000-0  10270-3 0  9011
      - TLE_L2=2 25544  51.6442  30.5153 0004445 220.3102 210.3102 15.48815327306221
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  sat-charlie:
    build: .
    command: python satellite_node.py
    depends_on:
      - ground-station
    volumes:
      - ./mission_data:/app/data
    environment:
      - SAT_NAME=SAT-CHARLIE
      - PYTHONUNBUFFERED=1
      - TLE_L1=1 25544U 98067A   26126.52495471  .00016717  00000-0  10270-3 0  9011
      - TLE_L2=2 25544  51.6442  50.5153 0004445 220.3102 210.3102 15.48815327306221
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  sat-delta:
    build: .
    command: python satellite_node.py
    depends_on:
      - ground-station
    volumes:
      - ./mission_data:/app/data
    environment:
      - SAT_NAME=SAT-DELTA
      - PYTHONUNBUFFERED=1
      - TLE_L1=1 25544U 98067A   26126.52495471  .00016717  00000-0  10270-3 0  9011
      - TLE_L2=2 25544  51.6442  70.5153 0004445 220.3102 210.3102 15.48815327306221
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: mission_control_db
    restart: always
    environment:
      - POSTGRES_USER=mission_user
      - POSTGRES_PASSWORD=space_password
      - POSTGRES_DB=mission_telemetry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: mission_control_viz
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  postgres_data:
  grafana_storage: